---
- name: Setting up redis component
  hosts: redis
  become: yes
  tasks:
   - name: Install redis rpm 
     ansible.builtin.shell: yum install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y
   - name: Enable redis repo 
     ansible.builtin.shell: yum module enable redis:remi-6.2 -y
   - name: Install redis package
     ansible.builtin.yum:
      name: redis
      state: installed
   - name: Allow remote connections to redis
     ansible.builtin.replace:
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
      path: /etc/redis.conf
   - name: Enable and Start redis service
     ansible.builtin.service:
      name: redis
      state: started
      enabled: true
...