---
- name: Setting up shipping component
  hosts: shipping
  become: yes
  tasks:
   - name: Install maven package
     ansible.builtin.yum:
      name: maven 
      state: installed
      update_cache: yes
   - name: check roboshop user exists or not 
     ansible.builtin.command: id roboshop
     register: output
     ignore_errors: true
   - name: print the command output 
     ansible.builtin.debug:
      msg: "output is:{{output}}"
   - name: print the exit status 
     ansible.builtin.debug:
      msg: "{{output.rc}}"
   - name: if roboshop user not exists,let's create 
     ansible.builtin.user:
      name: roboshop
     when: output.rc !=0
   - name: check if the app directory exists or not
     ansible.builtin.stat:
      path: /app
     register: directory
   - name: print the directory output
     ansible.builtin.debug:
      msg: "output is:{{directory}}"
   - name: if the app directory is not exists let's create it 
     ansible.builtin.file:
      name: /app
      state: directory
     when: directory.stats.exists == False
   - name: Download and unarchive application code
     ansible.builtin.unarchive:
      src: https://roboshop-builds.s3.amazonaws.com/shipping.zip
      dest: /app
      remote_src: yes
   - name: compile and build the package
     ansible.builtin.command: mvn clean package
     args:
      chdir: /app
   - name: rename the package 
     ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
     args:
      chdir: /app
   - name: copy the service 
     ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service
   - name: Start and Enable the daemon
     ansible.builtin.service:
      name: shipping
      state: started
      enabled: true
      daemon_reload: true
   - name: Install mysql client package
     ansible.builtin.yum:
      name: mysql
      state: installed
   - name: Load the schema into mysql
     ansible.builtin.shell: mysql -h roboshop-ansible-2024/inventory -uroot -pRoboShop@1 < /app/schema/shipping.sql
   - name: Restart shipping service
     ansible.builtin.service:
      name: shipping
      state: restarted
...

     