---
- name: Setting up user component
  hosts: user
  become: yes
  tasks:
   - name: Install NodeJS script which is provided by vendor 
     ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
   - name: Install NodeJS package 
     ansible.builtin.yum:
      name: nodejs
      state: installed
      update_cache: yes
   - name: Check roboshop user exists or not 
     ansible.builtin.command: id roboshop 
     register: output
     ignore_errors: true
   - name: print the command output 
     ansible.builtin.debug:
      msg: "output is:{{output}}"
   - name: print the exit status 
     ansible.builtin.debug:
      msg: "{{output.rc}}"
   - name: check the app directory exists or not 
     ansible.builtin.stat:
      path: /app
     register: directory
   - name: if app directory not exists create it 
     ansible.builtin.file:
      name: /app
      state: directory
     when: stat.directory.exists == False
   - name: Download the user application code
     ansible.builtin.get_url:
      url: curl -L -o /tmp/user.zip https://roboshop-builds.s3.amazonaws.com/user.zip
      dest: /tmp
   - name: Unzip user application code
     ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes
   - name: Install dependencies
     ansible.builtin.shell: npm install
     args:
      chdir: /app
   - name: copy user service
     ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service
   - name: Enable and start user service
     ansible.builtin.service:
      name: user
      state: started
      enabled: true
      daemon-reload: true
   - name: copy mongo.repo into yum.repo.d
     ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
   - name: Install mongo client package
     ansible.builtin.yum:
      name: mongodb-org-shell
      state: installed
   - name: Load schema into the mongodb
     ansible.builtin.shell: mongo --host roboshop-us-dev-db-mongodb-01.sivadevops.website </app/schema/user.js 
   - name: Restart user service
     ansible.builtin.service:
      name: user
      state: restarted
...